#! /bin/bash

# test if sourced or executed
if [ $_ == $0 ]; then
	echo "Use: source $0"
	exit 
fi

basepath="$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)")"

binpath="$basepath/bin"
libpath="$basepath/lib"
incpath="$basepath/include"
runpath="$basepath/runtime"

# PATH
export PATH=$binpath:$PATH
export PATH=$runpath:$PATH

# LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

export MPI_PATH=$binpath
export MPI_LIB=$libpath
export MPI_INC=$incpath
export MPI_HOME=$basepath
