#!/bin/bash



# set base and derivative directories
#basedir=$(dirname "$(dirname "$0")")

#libdir=$basedir/lib
libdir=$MPI_LIB
#incdir=$basedir/include
incdir=$MPI_INC

# assign CXX if not defined externally
if [ -z "$CXX" ]; then
	CXX="c++"
fi

# require arguments, something to compile
if [ "$#" -eq 0 ]; then
	$CXX
	exit
fi

$CXX "$@" -I$incdir -L$libdir -lexampi -pthread

exit $?
